# Generated by Django 5.0.3 on 2024-03-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('img', models.ImageField(upload_to='', verbose_name='upload_to_pics')),
            ],
        ),
    ]
