# Generated by Django 5.0.3 on 2024-03-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movies'),
            preserve_default=False,
        ),
    ]
