# Generated by Django 5.0.3 on 2024-03-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_reviews_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='movie',
            new_name='my_movie',
        ),
    ]
