# Generated by Django 5.0.3 on 2024-03-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_remove_reviews_username_reviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
