# Generated by Django 5.0.3 on 2024-03-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_remove_reviews_user_reviews_user_id_reviews_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
    ]
